### ISSUE TITLE
o is not defined in event-bus.js

### ISSUE THREAD

**Issue by yuzexing** [wendux/grace#24]
```
$off(eventName, cb){
  var cbs = global._graceBus[eventName] || [];
  if (cb) {
    for (var index = 0; index < cbs.length; ++index) {
      if (cb == o) {
        cbs.splice(index, 1);
        break
      }
    }
  } else {
    global._graceBus[eventName] = [];
  }
}
```
this is my code↓

```
onLoad() {
  this.$bus.$on('refreshVehicleInfo', this.refreshVehicleInfo);    
},
onUnload() {
  this.$bus.$off('refreshVehicleInfo', this.refreshVehicleInfo);
},
```

cause 

ReferenceError: o is not defined
    at Object.$off (http://127.0.0.1:11386/appservice/libs/grace.js:112:24)
    at r.onUnload (http://127.0.0.1:11386/appservice/subPackages/home/otherVehicleInfo/otherVehicleInfo.js:26:15)
    at r.e.(anonymous function) (http://127.0.0.1:11386/appservice/libs/grace.js:382:78)
    at r.t.(anonymous function) [as onUnload] (http://127.0.0.1:11386/appservice/libs/ald/ald-stat.js:29:30)
    at r.<anonymous> (http://127.0.0.1:11386/appservice/__dev__/WAService.js:18:1832)
    at N (http://127.0.0.1:11386/appservice/__dev__/WAService.js:17:12181)
    at W (http://127.0.0.1:11386/appservice/__dev__/WAService.js:17:12977)
    at G (http://127.0.0.1:11386/appservice/__dev__/WAService.js:17:14040)
    at Function.<anonymous> (http://127.0.0.1:11386/appservice/__dev__/WAService.js:17:16550)
    at http://127.0.0.1:11386/appservice/__dev__/WAService.js:17:22296

**Comment by wendux** [comment]
![image](https://user-images.githubusercontent.com/20411648/42719216-ce4391a6-8744-11e8-9de9-107abd05df79.png)

**Comment by yuzexing** [comment]
https://github.com/wendux/grace/blob/7b314ecc81262c5fb0bde8aa3ef5ce7059f07ed9/src/event-bus.js#L19

Has this been solved?
