### ISSUE TITLE
小程序1991，开发者工具运行demo正常，真机提示错误

### ISSUE THREAD

**Issue by yangbod** [wendux/grace#7]
错误堆栈
[publib]:3 thirdScriptError
origin is not defined;at pages/index/index page lifeCycleMethod onLoad function
ReferenceError: origin is not defined
    at hook (weapp:///grace/index.js:37:3)
    at e.onLoad (weapp:///grace/index.js:66:7)
    at e.origin.(anonymous function) (weapp:///grace/mixin.js:16:19)
    at e.<anonymous> ([publib]:17:30038)
    at B ([publib]:17:16312)
    at H ([publib]:17:18240)
    at G ([publib]:17:18506)
    at Function.<anonymous> ([publib]:17:21242)
    at [publib]:17:26966
    at [publib]:5:21737
errorReport @ [publib]:3
[publib]:3 thirdScriptError
Cannot set property '$hide' of undefined;at pages/index/index page lifeCycleMethod onShow function
TypeError: Cannot set property '$hide' of undefined
    at e.onShow (weapp:///grace/index.js:87:15)
    at e.origin.(anonymous function) (weapp:///grace/mixin.js:16:19)
    at e.<anonymous> ([publib]:17:30038)
    at B ([publib]:17:16324)
    at H ([publib]:17:18240)
    at G ([publib]:17:18506)
    at Function.<anonymous> ([publib]:17:21242)
    at [publib]:17:26966
    at [publib]:5:21737
    at Array.forEach (<anonymous>)

**Comment by wendux** [comment]
这个问题今天已经修复了，请更新代码

**Comment by yangbod** [comment]
完美了
